name: Run Real tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    # Trigger word 'javascript-largest-number'
    if: contains(github.event.head_commit.message, 'javascript-largest-number')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: node user/week01/exercises/day05/javascript-first-steps/largest-number.test.js
