name: "Tests: for Week02 Day03"

on:
  push:
    paths:
      - user/week02/exercises/day03/**

jobs:
  HTML_Table_Basics:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files_blank_template
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week02/exercises/day03/html_table_basics/blank-template.html"
          fail: true

      - name: Check file existence
        id: check_files_minimal_table
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week02/exercises/day03/html_table_basics/minimal-table.css"
          fail: true

      # - name: File exists
      #   if: steps.check_files_blank_template.outputs.files_exists == 'true'
      #   # Only runs if all of the files exists
      #   run: echo All solution files were submitted!
