name: "Week 04 - Day 3 CSS 2 & Performance | Test Exercise: 'Test your skills: Flexbox'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week04/exercises/day03/flexbox_skills/**
jobs:
  flexbox_skills:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Test your skills: Flexbox' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week04/exercises/day03/flexbox_skills/flexbox1-download.html, user/week04/exercises/day03/flexbox_skills/flexbox2-download.html, user/week04/exercises/day03/flexbox_skills/flexbox3-download.html, user/week04/exercises/day03/flexbox_skills/flexbox4-download.html"
          fail: true