name: "Week 06 - Day 2 JavaScript Core 1 | Test Exercise: 'JavaScript Strings'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week06/exercises/day02/task_4/**
jobs:
  task_4:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'JavaScript Strings' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week06/exercises/day02/task_4/strings.js, user/week06/exercises/day02/task_4/strings.html"
          fail: true