name: "Week 07 - Day 1 JavaScript Core 1 | Test Exercise: 'Booleans in JavaScript'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week07/exercises/day01/task_1/**
jobs:
  task_1:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Booleans in JavaScript' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week07/exercises/day01/task_1/booleans.js, user/week07/exercises/day01/task_1/booleans.html"
          fail: true