name: "Week 07 - Day 4 JavaScript Core 1 | Test Exercise: 'Test your skills: JavaScript Arrays'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week07/exercises/day04/task_5/**
jobs:
  task_5:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Test your skills: JavaScript Arrays' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week07/exercises/day04/task_5/arrays-skills.js, user/week07/exercises/day04/task_5/arrays-skills.html"
          fail: true