name: "Week 07 - Day 1 JavaScript Core 1 | Test Exercise: 'Creating Variables'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week07/exercises/day01/task_2/**
jobs:
  task_2:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Creating Variables' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week07/exercises/day01/task_2/creating-variables.js, user/week07/exercises/day01/task_2/creating-variables.html"
          fail: true