name: "Week 10 - Day 2 Web APIs 1: DOM | Test Exercise: 'Simple Manipulation - Part 01'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week10/exercises/day02/simple_manipulation/**
jobs:
  simple_manipulation:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Simple Manipulation - Part 01' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week10/exercises/day02/simple_manipulation/dom.html, user/week10/exercises/day02/simple_manipulation/dom.js"
          fail: true