name: "Week 11 - Day 1 Web APIs 2: Asynchronous Programming - Promises - JSON - Fetch API | Test Exercise: 'JSON Basics'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week11/exercises/day01/json_basics/**
jobs:
  json_basics:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'JSON Basics' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week11/exercises/day01/json_basics/json.html, user/week11/exercises/day01/json_basics/json.js"
          fail: true